      *Skeleton COBOL Copybook
       SELECT VUFLIX-MOVIE-LIST-FILE
               ASSIGN TO "VUFLIX-MOVIE-LIST.TXT"
               ORGANIZATION IS LINE SEQUENTIAL.
               
       SELECT VUFLIX-MOVIE-LIST-FILE-DAT
               ASSIGN TO "VUFLIX-MOVIE-LIST.DAT"
               ORGANIZATION IS LINE SEQUENTIAL.


