      *Skeleton COBOL Copybook - JARROD LEE - 3/20/14*
       SELECT MERCHANT-LOCATION-FILE
               ASSIGN TO 'MERCHANT-LOCATION.TXT'
               ORGANIZATION IS LINE SEQUENTIAL.
               
       SELECT MERCHANT-LOCATION-FILE-DAT
               ASSIGN TO 'MERCHANT-LOCATION.DAT'
               ORGANIZATION IS LINE SEQUENTIAL.


