      *Skeleton COBOL Copybook
       SELECT VUFLIX-MEMBER-FILE
               ASSIGN TO "VUFLIX-MEMBER.TXT"
               ORGANIZATION IS LINE SEQUENTIAL.
               
       SELECT VUFLIX-MEMBER-FILE-DAT
               ASSIGN TO "VUFLIX-MEMBER.DAT"
               ORGANIZATION IS LINE SEQUENTIAL.


